# config.yaml
data:
  train_path: ./data/train
  val_path: ./data/val_in
  batch_size: 8
  shuffle: true
  num_workers: 8
  transforms:
    - AgentCenter
  collate:
    - p_in
    # - v_in
    # - lane

