# # config.yaml
# data:
#   train_path: ./data/train
#   val_path: ./data/val_in
#   batch_size: 8
#   shuffle: true
#   num_workers: 8
#   transforms:
#     - AgentCenter
#   collate:
#     - p_in
#     # - v_in
#     # - lane

# # load data
# transform data
# collate data
# infer on data
# undo transform
# loss

num_epochs: 5

model: 
  name: SimpleMLP
  device: cuda
  hidden_size: [512, 512, 512, 512, 512, 512]
  dropout: 0.2

# config.yaml
data:
  train_path: ./data/train
  val_path: ./data/val_in
  batch_size: 32
  shuffle: true
  num_workers: 4

  coord_dims: 2
  input_timesteps: 19
  output_timesteps: 30
  features:
    lane: 0
    p_in: 0
    v_in: 0 # should be same as p_in (num agents being considered)

  transforms:
    - AgentCenter
