# # config.yaml
# data:
#   train_path: ./data/train
#   val_path: ./data/val_in
#   batch_size: 8
#   shuffle: true
#   num_workers: 8
#   transforms:
#     - AgentCenter
#   collate:
#     - p_in
#     # - v_in
#     # - lane

# # load data
# transform data
# collate data
# infer on data
# undo transform
# loss

num_epochs: 20

model: 
  name: SimpleMLP
  device: cuda
  hidden_size: [4096, 2048, 4096, 2048, 4096, 1024]
  dropout: 0.2

# config.yaml
data:
  train_path: ./data/train
  val_path: ./data/val_in
  batch_size: 64
  shuffle: true
  num_workers: 8

  train_val_split: 0.8

  coord_dims: 2
  input_timesteps: 19
  output_timesteps: 30
  features:
    lane: 20 # needs work
    p_in: 3
    v_in: 0 # should be same as p_in (num agents being considered)

    positional_embeddings: 3

  transforms:
    - AgentCenter
