model: 
  # name: SimpleMLP
  # device: cuda
  # hidden_size: [1024, 2048, 2048, 2048, 2048, 1024]
  # dropout: 0.2

  name: SimpleRNN
  device: cuda
  hidden_size: 512
  num_layers: 3
  dropout: 0.2

# config.yaml
data:
  train_path: ./data/train
  batch_size: 1
  shuffle: false
  num_workers: 1

  train_val_split: 1.0

  coord_dims: 2
  input_timesteps: 19
  output_timesteps: 30
  features:
    lane: 0
    p_in: 0
    v_in: 0 # should be same as p_in (num agents being considered)

    positional_embeddings: 0

  transforms:
    - AgentCenter
